Jenskinsfile: use nuttx container as emscripten requires xz to be installed
Fixes the error:
Error: tar (child): xz: Cannot exec: No such file or directory

Former-commit-id: 25fe13583e8a61c4f1bb673bf37ac195d0d2d403